config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'lists#index'

    resources :lists
    resources :items

    get 'complete', to: 'items#comlete'
    get 'incomplete', to: 'items#incomlete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  scope :complete, -> { where(done: true) }
  scope :incomplete, -> { where(done: false) }

  validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @list = List.find(params[:item][:list_id])
    @item = @list.items.create(item_params)
    redirect_to list_path(@list)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    list_id = @item.list_id
    if @item.update(item_params)
      redirect_to list_path(list_id)
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    list_id = @item.list_id
    @item.destroy

    redirect_to list_path(list_id)
  end

  def comlete
    @item = Item.find(params[:id])
    list_id = @item.list_id
    @item.update(done: true)

    redirect_to list_path(list_id)
  end

  def incomlete
    @item = Item.find(params[:id])
    list_id = @item.list_id
    @item.update(done: false)

    redirect_to list_path(list_id)
  end

  private def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
    @item = @list.items.new
  end

  def new
    @list = current_user.lists.build
  end

  def create
    @list = current_user.lists.build(lists_params)

    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(lists_params)
      redirect_to lists_path
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def lists_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <%= form.hidden_field :list_id, value: @item.list_id %>
  <p>
    <%= form.submit({:class => 'btn btn-success'})%>
  </p>
<% end %>

app/views/items/_item.html.erb
<strong><%= item.name %></strong>
<pre><strong>Description: </strong><%= item.description %></pre>
<%= link_to 'Edit Item', edit_item_path(item) %>
<%= link_to 'Delete Item', item_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<style>
  .todolist_bar_main a:link { color: black; text-decoration: none;}
  .todolist_bar_main a:visited { color: black;}
  .todolist_bar_main a:hover { color: black;}
  .todolist_bar_main a:active { color: black;}
  .todolist_bar a:link { color: white;  text-decoration: none;}
  .todolist_bar a:visited { color: white;}
  .todolist_bar a:hover { color: #F1F6FB;}
  .todolist_bar a:active { color: #F1F6FB;}
</style>
<html>
  <head>
    <title>TodoList</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="text-dark d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm ">
      <h2 class="my-0 mr-md-auto font-weight-bold todolist_bar_main"><%= link_to"ToDo Lists", lists_path%></h2>
      <nav class="my-2 my-md-0 mr-md-3">
         <span class="btn btn-primary  todolist_bar"><%= link_to 'New List', new_list_path %></span>
      </nav>
      <span class="btn btn-info  todolist_bar" ><%=link_to 'Sign in', new_user_session_path %></span>
      <span class="btn btn-info  todolist_bar" ><%=link_to('Logout', destroy_user_session_path, method: :delete)%></span>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: @list, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>
<%= render 'form' %>
<style>
   a:link { color: green; text-decoration: none;}
   a:visited { color: green; }
</style>
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<style>
  .todolist a:link {
    color: purple;
    background-color: transparent;
    text-decoration: none;
  }
  .todolist a:visited {
    color: purple;
  }
  .todolist a:hover {
    color: green;
  }
  .todolist a:active {
    color: green;
  }
  .todolist_action a:link {
    color: green;
    background-color: transparent;
    text-decoration: none;
  }
  .todolist_action a:visited {
    color: green;
  }
  .todolist_action a:hover {
    color: purple;
  }
  .todolist_action a:active {
    color: purple;
  }
</style>
<h1>All lists</h1>

<strong>Name:</strong>
<% @lists.each do |list| %>
  <div class="alert alert-info todolist">
    <%= link_to list.name, list_path(list) %>
    <p class="todolist_action">
      <%= link_to 'Edit List Name', edit_list_path(list) %>
      <%= link_to 'Delete List', list_path(list.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<style>
   a:link { color: green; text-decoration: none;}
   a:visited { color: green; }
</style>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h3>
  <strong>List name: </strong>
  <%= @list.name %>
</h3>

<h6><strong>Complete Items</strong></h6>
<% @list.items.complete.each do |item| %></td>
  <div class="alert alert-success">
    <% next if item.id.nil? %>
    <%= render item %>
    <%= link_to "Incomplete", incomplete_path(id: item.id), method: :get %>
  </div>
<% end %>

<h6> <strong>Incomplete Items</strong></h6>
<% @list.items.incomplete.each do |item| %></td>
  <div class="alert alert-primary">
    <% next if item.id.nil? %>
    <%= render item %>
    <%= link_to "Complete", complete_path(id: item.id), method: :get %>
  </div>
<% end %>
<br>
<h3>Add a item:</h3>
<%= render 'items/form' %>
<style>
  a:link { color: green; text-decoration: none;}
  a:visited { color: green; }
</style>
<%= link_to 'Back', lists_path %>